DELETE FROM CATEGORY;
INSERT INTO PUBLIC.CATEGORY (ID, NAME, PARENT_ID) VALUES (1, 'one', null);
INSERT INTO PUBLIC.CATEGORY (ID, NAME, PARENT_ID) VALUES (2, 'two', null);
INSERT INTO PUBLIC.CATEGORY (ID, NAME, PARENT_ID) VALUES (3, 'three', null);
INSERT INTO PUBLIC.CATEGORY (ID, NAME, PARENT_ID) VALUES (4, '1.1', 1);
INSERT INTO PUBLIC.CATEGORY (ID, NAME, PARENT_ID) VALUES (5, '1.2', 1);
INSERT INTO PUBLIC.CATEGORY (ID, NAME, PARENT_ID) VALUES (6, '1.3', 1);